"""ref tikets

Revision ID: 3088af411285
Revises: d4650b74233d
Create Date: 2025-11-22 09:11:35.581287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3088af411285'
down_revision: Union[str, Sequence[str], None] = 'd4650b74233d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('session_id', sa.String(length=100), nullable=False))
    op.drop_index(op.f('ix_tickets_user_identity'), table_name='tickets')
    op.create_index(op.f('ix_tickets_session_id'), 'tickets', ['session_id'], unique=False)
    op.drop_column('tickets', 'user_identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('user_identity', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tickets_session_id'), table_name='tickets')
    op.create_index(op.f('ix_tickets_user_identity'), 'tickets', ['user_identity'], unique=False)
    op.drop_column('tickets', 'session_id')
    # ### end Alembic commands ###
