"""ref tickets

Revision ID: 6e00478b09d3
Revises: ae175138cf4c
Create Date: 2025-11-21 12:42:05.151795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e00478b09d3'
down_revision: Union[str, Sequence[str], None] = 'ae175138cf4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('user_identity', sa.String(length=100), nullable=False))
    op.add_column('tickets', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('tickets', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('tickets', sa.Column('called_at', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tickets_user_identity'), 'tickets', ['user_identity'], unique=False)
    op.drop_column('tickets', 'client_identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('client_identity', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tickets_user_identity'), table_name='tickets')
    op.drop_column('tickets', 'completed_at')
    op.drop_column('tickets', 'called_at')
    op.drop_column('tickets', 'updated_at')
    op.drop_column('tickets', 'is_deleted')
    op.drop_column('tickets', 'notes')
    op.drop_column('tickets', 'user_identity')
    # ### end Alembic commands ###
