"""ref models

Revision ID: 74dab711249c
Revises: 6a5d426c3f16
Create Date: 2025-11-20 20:48:28.721551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74dab711249c'
down_revision: Union[str, Sequence[str], None] = '6a5d426c3f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('qr_code', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'events', ['qr_code'])
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'location')
    op.drop_column('events', 'start_time')
    op.drop_column('events', 'description')
    op.drop_column('events', 'end_time')
    op.add_column('queues', sa.Column('letter', sa.String(length=1), nullable=False))
    op.add_column('queues', sa.Column('current_pos', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('queues_qr_code_key'), 'queues', type_='unique')
    op.drop_column('queues', 'qr_code')
    op.drop_column('queues', 'name')
    op.drop_column('queues', 'current_size')
    op.drop_column('queues', 'max_participants')
    op.drop_column('queues', 'service_type')
    op.drop_column('queues', 'estimated_wait_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queues', sa.Column('estimated_wait_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('queues', sa.Column('service_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('queues', sa.Column('max_participants', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('queues', sa.Column('current_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('queues', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('queues', sa.Column('qr_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('queues_qr_code_key'), 'queues', ['qr_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('queues', 'current_pos')
    op.drop_column('queues', 'letter')
    op.add_column('events', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='unique')
    op.drop_column('events', 'qr_code')
    # ### end Alembic commands ###
