"""ref queues

Revision ID: ae175138cf4c
Revises: f2d9858d7196
Create Date: 2025-11-21 12:16:51.830536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae175138cf4c'
down_revision: Union[str, Sequence[str], None] = 'f2d9858d7196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queues', sa.Column('name', sa.String(length=10), nullable=False))
    op.add_column('queues', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('queues', sa.Column('current_position', sa.Integer(), nullable=False))
    op.add_column('queues', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('queues', 'current_pos')
    op.drop_column('queues', 'letter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queues', sa.Column('letter', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.add_column('queues', sa.Column('current_pos', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('queues', 'updated_at')
    op.drop_column('queues', 'current_position')
    op.drop_column('queues', 'is_deleted')
    op.drop_column('queues', 'name')
    # ### end Alembic commands ###
