"""ref events

Revision ID: f2d9858d7196
Revises: 74dab711249c
Create Date: 2025-11-21 12:00:29.589050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d9858d7196'
down_revision: Union[str, Sequence[str], None] = '74dab711249c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('code', sa.String(length=50), nullable=False))
    op.add_column('events', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('events', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('events', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_constraint(op.f('events_qr_code_key'), 'events', type_='unique')
    op.create_index(op.f('ix_events_code'), 'events', ['code'], unique=True)
    op.drop_column('events', 'qr_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('qr_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_events_code'), table_name='events')
    op.create_unique_constraint(op.f('events_qr_code_key'), 'events', ['qr_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('events', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'is_deleted')
    op.drop_column('events', 'code')
    # ### end Alembic commands ###
